apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cicd
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      hostAliases:
      - ip: "89.1.2.3"
        hostnames:
        - "jenkins.cicd"
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: gitlab-data
          mountPath: /etc/gitlab
          subPath: git-config
        - name: gitlab-data
          mountPath: /var/log/gitlab
          subPath: git-logs
        - name: gitlab-data
          mountPath: /var/opt/gitlab
          subPath: gitlab-data
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab