apiVersion: v1
kind: Service
metadata:
  namespace: cicd
  name: gitlab
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: ui
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    app: gitlab
