apiVersion: v1
kind: Service
metadata:
  namespace: cicd
  name: jenkins-slave
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
      name: slave
  selector:
    app: jenkins